env:
  global:
    - CC_TEST_REPORTER_ID=$CODE_CLIMATE_TOKEN

language: go

go:
  - 1.10.x

services:
  - docker

before_install:
  - go get -t ./...
  - docker-compose up -d

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -tags=acceptance -coverprofile c.out ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
